"""added search_elo to matches

Revision ID: 1214b4a80515
Revises: 7f9ea987f8a8
Create Date: 2026-10-04 18:25:53.756652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1214b4a80515'
down_revision: Union[str, Sequence[str], None] = '7f9ea987f8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('search_elo', sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'search_elo')
    # ### end Alembic commands ###
