"""Added placed before column to matches

Revision ID: 58ccc40b14a1
Revises: 1214b4a80515
Create Date: 2026-10-06 22:03:44.374875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ccc40b14a1'
down_revision: Union[str, Sequence[str], None] = '1214b4a80515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('player_placed_before', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'player_placed_before')
    # ### end Alembic commands ###
