"""Added match scores table.

Revision ID: 658a2c3167f8
Revises: 58ccc40b14a1
Create Date: 2026-10-09 23:25:48.763064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658a2c3167f8'
down_revision: Union[str, Sequence[str], None] = '58ccc40b14a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('lamp', sa.Enum('NO PLAY', 'FAILED', 'ASSIST CLEAR', 'EASY CLEAR', 'CLEAR', 'HARD CLEAR', 'EX HARD CLEAR', 'FULL COMBO', name='cleartypes', native_enum=False), nullable=False),
    sa.Column('grade', sa.String(length=8), nullable=False),
    sa.Column('percent', sa.Double(), nullable=True),
    sa.CheckConstraint("lamp IN ('NO PLAY', 'FAILED', 'ASSIST CLEAR', 'EASY CLEAR', 'CLEAR', 'HARD CLEAR', 'EX HARD CLEAR', 'FULL COMBO')", name='ck_match_scores_lamp'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_scores_match_id'), 'match_scores', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_scores_match_id'), table_name='match_scores')
    op.drop_table('match_scores')
    # ### end Alembic commands ###
