"""Added forfeited_at on matches.

Revision ID: 7800ad687bab
Revises: 8a10bc81e4be
Create Date: 2026-10-10 00:00:33.487376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7800ad687bab'
down_revision: Union[str, Sequence[str], None] = '8a10bc81e4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('forfeited_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'forfeited_at')
    # ### end Alembic commands ###
