"""added type to match model

Revision ID: 7f9ea987f8a8
Revises: 9d51379b633f
Create Date: 2026-10-04 18:01:03.980219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9ea987f8a8'
down_revision: Union[str, Sequence[str], None] = '9d51379b633f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('type', sa.Enum('casual', 'competitive', name='matchtype', native_enum=False), server_default='competitive', nullable=False))
    op.create_index(op.f('ix_matches_type'), 'matches', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_type'), table_name='matches')
    op.drop_column('matches', 'type')
    # ### end Alembic commands ###
