"""Added bp

Revision ID: 8a10bc81e4be
Revises: 658a2c3167f8
Create Date: 2026-10-09 23:27:59.373114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a10bc81e4be'
down_revision: Union[str, Sequence[str], None] = '658a2c3167f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_scores', sa.Column('bp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_scores', 'bp')
    # ### end Alembic commands ###
