"""add avoided charts

Revision ID: 9d51379b633f
Revises: e03dbf402b9c
Create Date: 2026-10-04 07:14:41.547737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d51379b633f'
down_revision: Union[str, Sequence[str], None] = 'e03dbf402b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_avoided_charts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.chart_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chart_id')
    )
    op.alter_column('matches', 'result',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('win', 'loss', name='matchresult', native_enum=False),
               existing_nullable=True)
    op.alter_column('matches', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('active', 'resolved', 'expired', 'cancelled', name='matchstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'status',
               existing_type=sa.Enum('active', 'resolved', 'expired', 'cancelled', name='matchstatus', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('matches', 'result',
               existing_type=sa.Enum('win', 'loss', name='matchresult', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.drop_table('user_avoided_charts')
    # ### end Alembic commands ###
