"""initial schema

Revision ID: e03dbf402b9c
Revises: 
Create Date: 2026-10-02 18:38:46.133994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e03dbf402b9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charts',
    sa.Column('chart_id', sa.String(), nullable=False),
    sa.Column('song_id', sa.String(), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('sg_ec', sa.Double(), nullable=True),
    sa.Column('sg_hc', sa.Double(), nullable=True),
    sa.Column('game', sa.String(length=16), nullable=False),
    sa.Column('playtype', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('chart_id')
    )
    op.create_index(op.f('ix_charts_game'), 'charts', ['game'], unique=False)
    op.create_index(op.f('ix_charts_md5'), 'charts', ['md5'], unique=False)
    op.create_index(op.f('ix_charts_playtype'), 'charts', ['playtype'], unique=False)
    op.create_index(op.f('ix_charts_sha256'), 'charts', ['sha256'], unique=False)
    op.create_index(op.f('ix_charts_song_id'), 'charts', ['song_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('tachi_api_key', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rating_seeds', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('uq_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('chart_ratings',
    sa.Column('chart_id', sa.String(), nullable=False),
    sa.Column('ladder', sa.String(length=8), nullable=False),
    sa.Column('rating', sa.Double(), nullable=False),
    sa.Column('rd', sa.Double(), nullable=False),
    sa.Column('volatility', sa.Double(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.chart_id'], ),
    sa.PrimaryKeyConstraint('chart_id', 'ladder')
    )
    op.create_table('chart_table_levels',
    sa.Column('chart_id', sa.String(), nullable=False),
    sa.Column('table_icon', sa.String(), nullable=False),
    sa.Column('table_level', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.chart_id'], ),
    sa.PrimaryKeyConstraint('chart_id', 'table_icon')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_run_after'), 'jobs', ['run_after'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.String(), nullable=False),
    sa.Column('rating_change', sa.Double(), nullable=True),
    sa.Column('ladder', sa.String(length=8), nullable=False),
    sa.Column('game', sa.String(length=32), nullable=False),
    sa.Column('playtype', sa.String(length=32), nullable=False),
    sa.Column('result', sa.Enum('win', 'loss', name='matchresult', native_enum=False, length=16), nullable=True),
    sa.Column('status', sa.Enum('active', 'resolved', 'expired', 'cancelled', name='matchstatus', native_enum=False, length=16), nullable=False),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('player_mmr_before', sa.Double(), nullable=True),
    sa.Column('player_mmr_after', sa.Double(), nullable=True),
    sa.Column('player_display_before', sa.Double(), nullable=True),
    sa.Column('player_display_after', sa.Double(), nullable=True),
    sa.Column('chart_rating_before', sa.Double(), nullable=True),
    sa.Column('chart_rating_after', sa.Double(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cutoff_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("result IN ('win', 'loss')", name='ck_matches_result'),
    sa.CheckConstraint("status IN ('active', 'resolved', 'expired', 'cancelled')", name='ck_matches_status'),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.chart_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_chart_id'), 'matches', ['chart_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_user_id'), 'matches', ['user_id'], unique=False)
    op.create_index('uq_matches_one_active', 'matches', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('player_ratings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=16), nullable=False),
    sa.Column('playtype', sa.String(length=8), nullable=False),
    sa.Column('ladder', sa.String(length=8), nullable=False),
    sa.Column('rating', sa.Double(), nullable=False),
    sa.Column('rd', sa.Double(), nullable=False),
    sa.Column('volatility', sa.Double(), nullable=False),
    sa.Column('display_rating', sa.Double(), nullable=False),
    sa.Column('placed', sa.Boolean(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'game', 'playtype', 'ladder')
    )
    op.create_table('user_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id')
    )
    op.create_index(op.f('ix_user_identities_user_id'), 'user_identities', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_identities_user_id'), table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_table('player_ratings')
    op.drop_index('uq_matches_one_active', table_name='matches', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_matches_user_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_chart_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_run_after'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('chart_table_levels')
    op.drop_table('chart_ratings')
    op.drop_index('uq_users_username_lower', table_name='users')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_charts_song_id'), table_name='charts')
    op.drop_index(op.f('ix_charts_sha256'), table_name='charts')
    op.drop_index(op.f('ix_charts_playtype'), table_name='charts')
    op.drop_index(op.f('ix_charts_md5'), table_name='charts')
    op.drop_index(op.f('ix_charts_game'), table_name='charts')
    op.drop_table('charts')
    # ### end Alembic commands ###
